[package]
name = "critic-index"
version = "0.1.0"
edition = "2024"
license = "MIT-0"
description = "Lower level parts of the segmentation, ocr and indexing for critic."
authors = ["Jonathan Schleucher"]

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
critic-config = { path = "../critic-config" }
critic-db = { path = "../critic-db" }
critic-format = { path = "../../critic-format" }
critic-shared = { path = "../critic-shared" }
pyo3 = { version = "0.26.0", features = ["auto-initialize"] }
quick-xml = { version = "0.38.0", features = ["serialize"]}
tantivy = "0.25.0"
tokio = { version = "1.46.1", default-features = false, features = ["time"] }
tracing = { version = "0.1.40" }
geo = "0.32.0"
