[package]
name = "critic-db"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["lib"]

[dependencies]
axum-login = { version = "0.17.0" }
critic-config = { path="../critic-config/" }
critic-shared = { path="../critic-shared/", features = ["ssr"] }
serde = { version = "1.0.219", features = ["derive"] }
sqlx = { version = "0.8.2", default-features = false, features = ["migrate", "time", "sqlite", "postgres", "runtime-tokio-rustls", "macros"] }
oauth2 = { version = "5.0.0" }
time = { version = "0.3.41" }
